#
# The cron job to take auto backups os the database
#
# Currently this is an Alpha feature of k8s 1.6.
# We will start using this once this moves to beta. (~ k8s 1.8)
#
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: pg-snapshot
spec:
  schedule: "0 * * * 0-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-snapshot
            image: eventyay/gcloud-utils:latest
            command:
            - /usr/bin/gcloud
            - compute disks snapshot pg-data-disk --zone us-west1-a
          restartPolicy: OnFailure
