version: '3.5'

services:
  fauna:
    image: fauna/faunadb:4.15.0
    container_name: faunadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/faunadb
      - ./log:/var/log/faunadb
      - ./config.yml:/etc/fauna.yml
    command: --config /etc/fauna.yml
    networks:
      - spnet

networks:
  spnet:
    external: yes
