#
# API Server service which will expose the API Server to the rest of the cluster
#
kind: Service
apiVersion: v1
metadata:
  name: api-server
  namespace: web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-server
