kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: redis
  labels:
    service: redis
spec:
  ports:
  - name: '6379'
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    service: redis
