kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: redis
        image: redis:3-alpine
        args:
        - redis-server
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "redis-cli set liveness-probe \"`date`\" | grep OK"
        ports:
        - containerPort: 6379
          protocol: TCP
      restartPolicy: Always
